config/routes.rb
Rails.application.routes.draw do
  # active_admin urls
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # categories controller
  resources :categories

  # items controller
  resources :items

  # users could sign up multiple times
  resources :users

  # users can only make 1 session
  resource :session

  # users can only edit 1 account
  resource :account

  get 'about', to: 'pages#about'
  root 'pages#home'

  get 'download', to: 'items#download'
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :category_items, dependent: :destroy
  has_many :items, through: :category_items

  validates :title, presence: true
  validates :title, uniqueness: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/index.html.erb
<h1>Categories</h1>
<% @categories.each do |category| %>
  <p>
    <%= link_to category.title, category_path(category) %>
  </p>
<% end %>

app/views/categories/show.html.erb
<h1><%= @category.title %></h1>
<div class="items-grid">
  <%= render partial: "items/item", collection: @category.items %>
</div>
<p>
  <%= link_to "Back to all categories", categories_path %>
</p>