config/routes.rb
Rails.application.routes.draw do
  # active_admin urls
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # categories controller
  resources :categories

  # items controller
  resources :items

  # users could sign up multiple times
  resources :users

  # users can only make 1 session
  resource :session

  # users can only edit 1 account
  resource :account

  get 'about', to: 'pages#about'
  root 'pages#home'

  get 'download', to: 'items#download'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Source</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js" type="text/javascript"></script>
    <script src="https://js.stripe.com/v3/"></script>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:success].present? %>
      <div class="success">
        <%= flash[:success] %>
      </div>
    <% end %>
    <% if flash[:error].present? %>
      <div class="error">
        <%= flash[:error] %>
      </div>
    <% end %>

    <header>
    <% unless controller_name == 'items' && action_name == 'show'  %>
      <%= link_to root_path do %>
        <h1>Source</h1>
      <% end %>
      <% else %>
       <%= link_to items_path do %>
        <h1>Source</h1>
      <% end %>
    <% end %>

      <nav>
        <% if is_logged_in? %>
          <strong>
            <%= @current_user.username %>
          </strong>
          <%= link_to "All photos", items_path %>
          <%= link_to "Categories", categories_path %>
          <%= link_to "Account", edit_account_path %>
          <%= link_to "Log out", session_path, method: :delete %>
        <% else %>
          <%= link_to "Sign up", new_user_path %>
          <%= link_to "Log in", new_session_path %>
        <% end %>
      </nav>
    </header>

    <div id="content">
      <%= yield %>
    </div>

    <div id="footer">
      <footer>
        The images on this website were downloaded from <a href="https://unsplash.com/" target="_blank">Unsplash</a>
      </footer>
    </div>

  </body>
</html>