config/routes.rb
Rails.application.routes.draw do
  # active_admin urls
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # categories controller
  resources :categories

  # items controller
  resources :items

  # users could sign up multiple times
  resources :users

  # users can only make 1 session
  resource :session

  # users can only edit 1 account
  resource :account

  get 'about', to: 'pages#about'
  root 'pages#home'

  get 'download', to: 'items#download'
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def edit
    # @current_user comes from application controller
    @user = @current_user
  end

  def update
    @user = @current_user

    if @user.update_with_stripe(form_params)
      flash[:success] = 'Your account has been updated'
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def destroy
    # deletes and unsubscribes (from Stripe and the database)
    @current_user.destroy_and_unsubscribe

    # remove the subscription
    # delete the current user
    # remove the session
    reset_session
    # redirect to home page
    redirect_to root_path
  end

  private
  def form_params
    params.require(:user).permit(:subscription_plan)
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/edit.html.erb
<h1>Edit account</h1>
<%= simple_form_for @user, url: account_path do |f| %>
  <%= f.input :subscription_plan, as: :select, collection: [['Basic subscription - $9.99/month', 'basic'], ['Pro subscription - $19.99/month', 'pro']], include_blank: false %> <%#= it will pass to the database the lowercase version and show the user the upcase one%>
  <%= f.button :submit, "Update account" %>
<% end %>
<p>
  <%= link_to "Delete account", account_path, method: :delete, data: { confirm: "Are you sure you want to delete your account?" } %>
</p>